default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: inventory
  username: postgres
  password: root



test:
  <<: *default
  database: inventory-test
  username: postgres
  password: root

production:
  <<: *default
  database: inventory-production
  username: postgres
  password: <%= ENV["INVENTORY_API_DATABASE_PASSWORD"] %>

