default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: inventory-api
  username: postgres
  password: root

test:
  <<: *default
  database: inventory_api_test
  username: postgres
  password: root

production:
  <<: *default
  database: inventory_api_production
  username: postgresql
  password: <%= ENV["RESTAURANT_API_DATABASE_PASSWORD"] %>

